/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Dashboard */
        get: operations["api_dashboard_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Daily Runs */
        get: operations["list_daily_runs_daily_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Picks */
        get: operations["list_picks_picks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/picks/{pick_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pick */
        get: operations["get_pick_picks__pick_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/picks/{pick_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Pick Status
         * @description Solo permite marcar void un pick en pending (escritura acotada).
         */
        patch: operations["patch_pick_status_picks__pick_id__status_patch"];
        trace?: never;
    };
    "/backtest-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtest Runs */
        get: operations["list_backtest_runs_backtest_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api List Users */
        get: operations["api_list_users_users_get"];
        put?: never;
        /** Api Create User */
        post: operations["api_create_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Get User */
        get: operations["api_get_user_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/bankroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Api Put User Bankroll */
        put: operations["api_put_user_bankroll_users__user_id__bankroll_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Bootstrap Users */
        post: operations["api_bootstrap_users_users_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-runs/{daily_run_id}/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Tracking Board */
        get: operations["api_tracking_board_daily_runs__daily_run_id__board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/picks/{pick_id}/taken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Api Put Pick Taken */
        put: operations["api_put_pick_taken_users__user_id__picks__pick_id__taken_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/suggested-combos/{combo_id}/taken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Api Put Combo Taken */
        put: operations["api_put_combo_taken_users__user_id__suggested_combos__combo_id__taken_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-runs/{daily_run_id}/suggested-combos/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Regenerate Combos */
        post: operations["api_regenerate_combos_daily_runs__daily_run_id__suggested_combos_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-runs/{daily_run_id}/pick-baselines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Ensure Baselines */
        post: operations["api_ensure_baselines_daily_runs__daily_run_id__pick_baselines_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/picks/{pick_id}/signal-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Signal Check */
        post: operations["api_signal_check_picks__pick_id__signal_checks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestRunOut */
        BacktestRunOut: {
            /** Backtest Run Id */
            backtest_run_id: number;
            /** Range Start */
            range_start: string;
            /** Range End */
            range_end: string;
            /** Strategy Version */
            strategy_version: string;
            /** Created At Utc */
            created_at_utc: string;
            /** Metrics Json */
            metrics_json: unknown | null;
        };
        /** BacktestRunPage */
        BacktestRunPage: {
            /** Items */
            items: components["schemas"]["BacktestRunOut"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** ComboLegOut */
        ComboLegOut: {
            /** Pick Id */
            pick_id: number;
            /** Leg Order */
            leg_order: number;
            /** Event Id */
            event_id: number;
            /** Market */
            market: string;
            /** Selection */
            selection: string;
        };
        /** DailyRunBoardOut */
        DailyRunBoardOut: {
            /** Daily Run Id */
            daily_run_id: number;
            /** Run Date */
            run_date: string;
            /** Sport */
            sport: string;
            /** Status */
            status: string;
        };
        /** DailyRunOut */
        DailyRunOut: {
            /** Daily Run Id */
            daily_run_id: number;
            /** Run Date */
            run_date: string;
            /** Sport */
            sport: string;
            /** Created At Utc */
            created_at_utc: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "complete" | "failed";
        };
        /** DailyRunPage */
        DailyRunPage: {
            /** Items */
            items: components["schemas"]["DailyRunOut"][];
            /**
             * Next Cursor
             * @description Siguiente cursor (daily_run_id): enviar como query `cursor` para la página siguiente.
             */
            next_cursor?: number | null;
        };
        /** DashboardBundleOut */
        DashboardBundleOut: {
            summary: components["schemas"]["DashboardSummaryBlock"];
            /** Recent */
            recent: components["schemas"]["DashboardRecentPick"][];
        };
        /**
         * DashboardPerformanceBlock
         * @description Todos los picks del día vs tomados vs no tomados (requiere usuario para el cruce).
         */
        DashboardPerformanceBlock: {
            totals: components["schemas"]["DashboardPerformanceSplit"];
            taken: components["schemas"]["DashboardPerformanceSplit"];
            not_taken: components["schemas"]["DashboardPerformanceSplit"];
        };
        /**
         * DashboardPerformanceSplit
         * @description Conteos por resultado efectivo (prioriza cierre usuario + pick_results).
         */
        DashboardPerformanceSplit: {
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Pending */
            pending: number;
        };
        /** DashboardRecentPick */
        DashboardRecentPick: {
            /** Pick Id */
            pick_id: number;
            /** Daily Run Id */
            daily_run_id: number;
            /** Event Id */
            event_id: number;
            /** Market */
            market: string;
            /** Selection */
            selection: string;
            /** Picked Value */
            picked_value: number | null;
            /** Created At Utc */
            created_at_utc: string;
            /**
             * Outcome
             * @description Resultado efectivo (prioriza cierre manual del usuario).
             */
            outcome?: ("win" | "loss" | "pending") | null;
            /**
             * Outcome System
             * @description Solo validación automática (pick_results), si existe.
             */
            outcome_system?: ("win" | "loss" | "pending") | null;
            /**
             * User Outcome
             * @description Cierre declarado por el usuario, si lo hubo.
             */
            user_outcome?: ("win" | "loss" | "pending") | null;
            /** User Taken */
            user_taken?: boolean | null;
            /** Risk Category */
            risk_category?: string | null;
            /** Decision Origin */
            decision_origin?: string | null;
            /** Stake Amount */
            stake_amount?: number | null;
            /** Event Label */
            event_label?: string | null;
            /** League */
            league?: string | null;
            /** Kickoff Display */
            kickoff_display?: string | null;
            /** Kickoff At Utc */
            kickoff_at_utc?: string | null;
            /** Selection Display */
            selection_display?: string | null;
            /**
             * Odds Reference
             * @description Metadatos del modelo (edge, confianza, razón, etc.)
             */
            odds_reference?: unknown | null;
        };
        /** DashboardSummaryBlock */
        DashboardSummaryBlock: {
            /** Run Date */
            run_date: string;
            /** Picks Total */
            picks_total: number;
            /** Outcome Wins */
            outcome_wins: number;
            /** Outcome Losses */
            outcome_losses: number;
            /** Outcome Pending */
            outcome_pending: number;
            /** Picks Taken Count */
            picks_taken_count: number;
            /**
             * Taken Outcome Wins
             * @default 0
             */
            taken_outcome_wins: number;
            /**
             * Taken Outcome Losses
             * @default 0
             */
            taken_outcome_losses: number;
            /**
             * Taken Outcome Pending
             * @default 0
             */
            taken_outcome_pending: number;
            performance: components["schemas"]["DashboardPerformanceBlock"];
            /**
             * Bankroll Cop
             * @description Saldo en servidor (`users.bankroll_cop`); se ajusta con wins/loss de picks tomados.
             */
            bankroll_cop?: number | null;
            /** Net Pl Estimate */
            net_pl_estimate?: number | null;
            /**
             * Has Stake Data
             * @default false
             */
            has_stake_data: boolean;
        };
        /** EnsureBaselinesResponse */
        EnsureBaselinesResponse: {
            /** Ok */
            ok: boolean;
            /** Daily Run Id */
            daily_run_id: number;
            /** Baselines Inserted */
            baselines_inserted: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Ok */
            ok: boolean;
            /** Db Path */
            db_path: string;
        };
        /**
         * PickDetail
         * @description Mismo shape que lista pero explícito para OpenAPI / detalle.
         */
        PickDetail: {
            /** Pick Id */
            pick_id: number;
            /** Daily Run Id */
            daily_run_id: number;
            /** Event Id */
            event_id: number;
            /** Market */
            market: string;
            /** Selection */
            selection: string;
            /** Picked Value */
            picked_value: number | null;
            /** Odds Reference */
            odds_reference: unknown;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "validated" | "void";
            /** Created At Utc */
            created_at_utc: string;
            /** Idempotency Key */
            idempotency_key: string;
            result: components["schemas"]["PickResultOut"] | null;
            /**
             * User Taken
             * @description Si se envía user_id en el board, indica si el usuario marcó ‘tomado’.
             */
            user_taken?: boolean | null;
            /** Risk Category */
            risk_category?: string | null;
            /** Decision Origin */
            decision_origin?: string | null;
            /** Stake Amount */
            stake_amount?: number | null;
            /**
             * User Outcome
             * @description Cierre manual (omitir en PATCH parcial para conservar el valor guardado).
             */
            user_outcome?: ("win" | "loss" | "pending") | null;
            /**
             * Realized Return Cop
             * @description Ganancia bruta en COP persistida solo si el resultado efectivo es win.
             */
            realized_return_cop?: number | null;
            /**
             * Event Label
             * @description Partido A vs B (desde event_features del run)
             */
            event_label?: string | null;
            /** League */
            league?: string | null;
            /**
             * Kickoff Display
             * @description Hora de inicio del partido en Colombia (p. ej. 18:30 · hora Colombia).
             */
            kickoff_display?: string | null;
            /**
             * Kickoff At Utc
             * @description Inicio del partido en ISO 8601 UTC (Z). Para bloquear edición de tomé/monto tras +100 min.
             */
            kickoff_at_utc?: string | null;
            /**
             * Run Date
             * @description YYYY-MM-DD del daily_run (día del análisis / listado).
             */
            run_date?: string | null;
        };
        /** PickPage */
        PickPage: {
            /** Items */
            items: components["schemas"]["PickSummary"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** PickResultOut */
        PickResultOut: {
            /** Validated At Utc */
            validated_at_utc: string;
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /** Result 1X2 */
            result_1x2: ("1" | "X" | "2") | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "win" | "loss" | "pending";
            /** Evidence Json */
            evidence_json: unknown;
        };
        /**
         * PickStatusPatch
         * @description Escritura acotada: solo void desde operaciones manuales locales.
         */
        PickStatusPatch: {
            /**
             * Status
             * @constant
             */
            status: "void";
        };
        /** PickStatusPatchResponse */
        PickStatusPatchResponse: {
            /** Ok */
            ok: boolean;
            /** Pick Id */
            pick_id: number;
            /** Status */
            status: string;
        };
        /** PickSummary */
        PickSummary: {
            /** Pick Id */
            pick_id: number;
            /** Daily Run Id */
            daily_run_id: number;
            /** Event Id */
            event_id: number;
            /** Market */
            market: string;
            /** Selection */
            selection: string;
            /** Picked Value */
            picked_value: number | null;
            /** Odds Reference */
            odds_reference: unknown;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "validated" | "void";
            /** Created At Utc */
            created_at_utc: string;
            /** Idempotency Key */
            idempotency_key: string;
            result: components["schemas"]["PickResultOut"] | null;
            /**
             * User Taken
             * @description Si se envía user_id en el board, indica si el usuario marcó ‘tomado’.
             */
            user_taken?: boolean | null;
            /** Risk Category */
            risk_category?: string | null;
            /** Decision Origin */
            decision_origin?: string | null;
            /** Stake Amount */
            stake_amount?: number | null;
            /**
             * User Outcome
             * @description Cierre manual (omitir en PATCH parcial para conservar el valor guardado).
             */
            user_outcome?: ("win" | "loss" | "pending") | null;
            /**
             * Realized Return Cop
             * @description Ganancia bruta en COP persistida solo si el resultado efectivo es win.
             */
            realized_return_cop?: number | null;
            /**
             * Event Label
             * @description Partido A vs B (desde event_features del run)
             */
            event_label?: string | null;
            /** League */
            league?: string | null;
            /**
             * Kickoff Display
             * @description Hora de inicio del partido en Colombia (p. ej. 18:30 · hora Colombia).
             */
            kickoff_display?: string | null;
            /**
             * Kickoff At Utc
             * @description Inicio del partido en ISO 8601 UTC (Z). Para bloquear edición de tomé/monto tras +100 min.
             */
            kickoff_at_utc?: string | null;
            /**
             * Run Date
             * @description YYYY-MM-DD del daily_run (día del análisis / listado).
             */
            run_date?: string | null;
        };
        /** RegenerateCombosResponse */
        RegenerateCombosResponse: {
            /** Ok */
            ok: boolean;
            /** Daily Run Id */
            daily_run_id: number;
            /** Suggested Combo Ids */
            suggested_combo_ids: number[];
        };
        /** SignalCheckBody */
        SignalCheckBody: {
            /**
             * Slot
             * @description morning | afternoon | manual | otro
             */
            slot: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "unknown";
            /** Detail */
            detail?: unknown | null;
        };
        /** SignalCheckOut */
        SignalCheckOut: {
            /** Ok */
            ok: boolean;
            /** Check Id */
            check_id: number;
        };
        /** SuggestedComboOut */
        SuggestedComboOut: {
            /** Suggested Combo Id */
            suggested_combo_id: number;
            /** Daily Run Id */
            daily_run_id: number;
            /** Rank Order */
            rank_order: number;
            /** Created At Utc */
            created_at_utc: string;
            /** Strategy Note */
            strategy_note: string | null;
            /** Legs */
            legs: components["schemas"]["ComboLegOut"][];
            /** User Taken */
            user_taken?: boolean | null;
            /**
             * User Stake Amount
             * @description Monto en COP registrado para esta combinada.
             */
            user_stake_amount?: number | null;
            /**
             * User Outcome
             * @description Cierre manual del usuario, si existe.
             */
            user_outcome?: ("win" | "loss" | "pending") | null;
            /**
             * Outcome From Legs
             * @description Resultado lógico si todas las piernas ganan / alguna pierde / resto pendiente.
             * @enum {string}
             */
            outcome_from_legs: "win" | "loss" | "pending";
            /**
             * Outcome Effective
             * @description Prioriza user_outcome; si no, outcome_from_legs.
             * @enum {string}
             */
            outcome_effective: "win" | "loss" | "pending";
        };
        /** TrackingBoardOut */
        TrackingBoardOut: {
            run: components["schemas"]["DailyRunBoardOut"];
            /** User Id */
            user_id: number;
            /** Picks */
            picks: components["schemas"]["PickSummary"][];
            /** Suggested Combos */
            suggested_combos: components["schemas"]["SuggestedComboOut"][];
        };
        /** UserBankrollBody */
        UserBankrollBody: {
            /**
             * Bankroll Cop
             * @description Nuevo bankroll en COP; null borra el valor guardado.
             */
            bankroll_cop?: number | null;
        };
        /** UserComboTakenBody */
        UserComboTakenBody: {
            /** Taken */
            taken: boolean;
            /** Stake Amount */
            stake_amount?: number | null;
            /**
             * User Outcome
             * @description Cierre manual de la combinada; omitir para no cambiar el guardado.
             */
            user_outcome?: ("win" | "loss" | "pending") | null;
            /**
             * User Outcome Auto
             * @description Si true, usa solo el resultado inferido de las piernas.
             * @default false
             */
            user_outcome_auto: boolean;
        };
        /** UserCreate */
        UserCreate: {
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
        };
        /** UserOut */
        UserOut: {
            /** User Id */
            user_id: number;
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
            /** Created At Utc */
            created_at_utc: string;
            /**
             * Bankroll Cop
             * @description Bankroll de referencia en COP (persistido en servidor).
             */
            bankroll_cop?: number | null;
        };
        /** UserPickTakenBody */
        UserPickTakenBody: {
            /** Taken */
            taken: boolean;
            /** Notes */
            notes?: string | null;
            /** Risk Category */
            risk_category?: ("escalonada" | "segura" | "balanceada" | "arriesgada" | "justificada") | null;
            /** Decision Origin */
            decision_origin?: ("analizada" | "intuicion" | "impulso") | null;
            /** Stake Amount */
            stake_amount?: number | null;
            /**
             * User Outcome
             * @description Tu resultado; no enviar el campo para no modificar el cierre guardado.
             */
            user_outcome?: ("win" | "loss" | "pending") | null;
            /**
             * User Outcome Auto
             * @description Si true, quita el cierre manual (solo score/API automática).
             * @default false
             */
            user_outcome_auto: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    api_dashboard_dashboard_get: {
        parameters: {
            query?: {
                /** @description YYYY-MM-DD (default: hoy en el servidor) */
                run_date?: string | null;
                /** @description Para métricas ‘tomé’ / stake / P/L estimado */
                user_id?: number | null;
                /** @description Si true, la lista reciente solo incluye picks marcados como tomados */
                only_taken?: boolean;
            };
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardBundleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_daily_runs_daily_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Keyset estable: daily_run_id estrictamente menor que este valor */
                cursor?: number | null;
                run_date?: string | null;
                sport?: string | null;
                status?: string | null;
            };
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyRunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_picks_picks_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Keyset estable: pick_id estrictamente menor que este valor */
                cursor?: number | null;
                daily_run_id?: number | null;
                status?: string | null;
            };
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pick_picks__pick_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path: {
                pick_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_pick_status_picks__pick_id__status_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path: {
                pick_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickStatusPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickStatusPatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtest_runs_backtest_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Keyset estable: backtest_run_id estrictamente menor que este valor */
                cursor?: number | null;
            };
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_list_users_users_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_create_user_users_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_user_users__user_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_put_user_bankroll_users__user_id__bankroll_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserBankrollBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_bootstrap_users_users_bootstrap_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_tracking_board_daily_runs__daily_run_id__board_get: {
        parameters: {
            query: {
                /** @description Usuario que ve el tablero */
                user_id: number;
            };
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path: {
                daily_run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingBoardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_put_pick_taken_users__user_id__picks__pick_id__taken_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path: {
                user_id: number;
                pick_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPickTakenBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_put_combo_taken_users__user_id__suggested_combos__combo_id__taken_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path: {
                user_id: number;
                combo_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserComboTakenBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_regenerate_combos_daily_runs__daily_run_id__suggested_combos_regenerate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path: {
                daily_run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegenerateCombosResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_ensure_baselines_daily_runs__daily_run_id__pick_baselines_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path: {
                daily_run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnsureBaselinesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_signal_check_picks__pick_id__signal_checks_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Local-Api-Key"?: string | null;
            };
            path: {
                pick_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalCheckBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
