"""bt2_odds_unique_constraint

Revision ID: 1240c2fcc453
Revises: 9b79b90c69a1
Create Date: 2026-04-06 20:16:25.787588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1240c2fcc453'
down_revision: Union[str, Sequence[str], None] = '9b79b90c69a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bt2_odds_event_market_sel_book', 'bt2_odds_snapshot', ['event_id', 'market', 'selection', 'bookmaker'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bt2_odds_event_market_sel_book', 'bt2_odds_snapshot', type_='unique')
    # ### end Alembic commands ###
