"""initial snapshot tables

Revision ID: 15ee91ad0d69
Revises: 
Create Date: 2026-04-05 20:27:03.458798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15ee91ad0d69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bt2_event_identity_map',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sportmonks_fixture_id', sa.Integer(), nullable=True),
    sa.Column('theoddsapi_event_id', sa.String(length=100), nullable=True),
    sa.Column('home_team', sa.String(length=200), nullable=True),
    sa.Column('away_team', sa.String(length=200), nullable=True),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('league_slug', sa.String(length=100), nullable=True),
    sa.Column('mapped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.String(length=20), server_default='low', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_sportmonks_fixtures',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('fixture_date', sa.Date(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('home_team', sa.String(length=200), nullable=True),
    sa.Column('away_team', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_sportmonks_fixtures_fixture_date'), 'raw_sportmonks_fixtures', ['fixture_date'], unique=False)
    op.create_index(op.f('ix_raw_sportmonks_fixtures_fixture_id'), 'raw_sportmonks_fixtures', ['fixture_id'], unique=True)
    op.create_table('raw_theoddsapi_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('sport_key', sa.String(length=100), nullable=True),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team', sa.String(length=200), nullable=True),
    sa.Column('away_team', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_theoddsapi_snapshots_commence_time'), 'raw_theoddsapi_snapshots', ['commence_time'], unique=False)
    op.create_index(op.f('ix_raw_theoddsapi_snapshots_sport_key'), 'raw_theoddsapi_snapshots', ['sport_key'], unique=False)
    op.create_index('ix_theoddsapi_sport_commence', 'raw_theoddsapi_snapshots', ['sport_key', 'commence_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_theoddsapi_sport_commence', table_name='raw_theoddsapi_snapshots')
    op.drop_index(op.f('ix_raw_theoddsapi_snapshots_sport_key'), table_name='raw_theoddsapi_snapshots')
    op.drop_index(op.f('ix_raw_theoddsapi_snapshots_commence_time'), table_name='raw_theoddsapi_snapshots')
    op.drop_table('raw_theoddsapi_snapshots')
    op.drop_index(op.f('ix_raw_sportmonks_fixtures_fixture_id'), table_name='raw_sportmonks_fixtures')
    op.drop_index(op.f('ix_raw_sportmonks_fixtures_fixture_date'), table_name='raw_sportmonks_fixtures')
    op.drop_table('raw_sportmonks_fixtures')
    op.drop_table('bt2_event_identity_map')
    # ### end Alembic commands ###
