"""cdm_four_tables_sprint03

Revision ID: 329bd4b9d494
Revises: 15ee91ad0d69
Create Date: 2026-04-06 16:03:24.771330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329bd4b9d494'
down_revision: Union[str, Sequence[str], None] = '15ee91ad0d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bt2_leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=20), server_default='unknown', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sportmonks_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sportmonks_id')
    )
    op.create_table('bt2_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('sportmonks_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['bt2_leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sportmonks_id')
    )
    op.create_table('bt2_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sportmonks_fixture_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='scheduled', nullable=False),
    sa.Column('result_home', sa.Integer(), nullable=True),
    sa.Column('result_away', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['bt2_teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['bt2_teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['bt2_leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sportmonks_fixture_id')
    )
    op.create_index('ix_bt2_events_kickoff', 'bt2_events', ['kickoff_utc'], unique=False)
    op.create_index('ix_bt2_events_status_kickoff', 'bt2_events', ['status', 'kickoff_utc'], unique=False)
    op.create_table('bt2_odds_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('selection', sa.String(length=100), nullable=False),
    sa.Column('odds', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['bt2_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bt2_odds_event_market', 'bt2_odds_snapshot', ['event_id', 'market'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bt2_odds_event_market', table_name='bt2_odds_snapshot')
    op.drop_table('bt2_odds_snapshot')
    op.drop_index('ix_bt2_events_status_kickoff', table_name='bt2_events')
    op.drop_index('ix_bt2_events_kickoff', table_name='bt2_events')
    op.drop_table('bt2_events')
    op.drop_table('bt2_teams')
    op.drop_table('bt2_leagues')
    # ### end Alembic commands ###
