"""bt2_daily_picks_sprint04_addendum

Revision ID: 33ad702e05ab
Revises: 7a609e85688b
Create Date: 2026-04-06 22:09:45.441537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ad702e05ab'
down_revision: Union[str, Sequence[str], None] = '7a609e85688b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bt2_daily_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('operating_day_key', sa.String(length=10), nullable=False),
    sa.Column('access_tier', sa.String(length=10), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('suggested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['bt2_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bt2_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', 'operating_day_key', name='uq_daily_picks_user_event_day')
    )
    op.create_index('ix_daily_picks_user_day', 'bt2_daily_picks', ['user_id', 'operating_day_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_picks_user_day', table_name='bt2_daily_picks')
    op.drop_table('bt2_daily_picks')
    # ### end Alembic commands ###
