"""behavioral_domain_sprint04

Revision ID: 7a609e85688b
Revises: 1240c2fcc453
Create Date: 2026-04-06 21:27:46.864780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a609e85688b'
down_revision: Union[str, Sequence[str], None] = '1240c2fcc453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bt2_bankroll_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('balance_units', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bt2_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bt2_bankroll_user_date', 'bt2_bankroll_snapshots', ['user_id', 'snapshot_date'], unique=False)
    op.create_table('bt2_behavioral_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_loss_avoided_units', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bt2_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bt2_dp_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('delta_dp', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('balance_after_dp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bt2_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bt2_dp_ledger_user', 'bt2_dp_ledger', ['user_id'], unique=False)
    op.create_table('bt2_operating_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('operating_day_key', sa.String(length=10), nullable=False),
    sa.Column('station_opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('station_closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('grace_until_iso', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['bt2_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'operating_day_key', name='uq_bt2_opsession_user_day')
    )
    op.create_index('ix_bt2_opsession_user_status', 'bt2_operating_sessions', ['user_id', 'status'], unique=False)
    op.create_table('bt2_user_settings',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('risk_per_pick_pct', sa.Numeric(precision=5, scale=2), server_default='2.00', nullable=False),
    sa.Column('dp_unlock_premium_threshold', sa.Integer(), server_default='50', nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='America/Bogota', nullable=False),
    sa.Column('display_currency', sa.String(length=10), server_default='COP', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bt2_users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('bt2_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('selection', sa.String(length=50), nullable=False),
    sa.Column('odds_taken', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('stake_units', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_home', sa.Integer(), nullable=True),
    sa.Column('result_away', sa.Integer(), nullable=True),
    sa.Column('pnl_units', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['bt2_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bt2_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bt2_picks_event', 'bt2_picks', ['event_id'], unique=False)
    op.create_index('ix_bt2_picks_user_status', 'bt2_picks', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bt2_picks_user_status', table_name='bt2_picks')
    op.drop_index('ix_bt2_picks_event', table_name='bt2_picks')
    op.drop_table('bt2_picks')
    op.drop_table('bt2_user_settings')
    op.drop_index('ix_bt2_opsession_user_status', table_name='bt2_operating_sessions')
    op.drop_table('bt2_operating_sessions')
    op.drop_index('ix_bt2_dp_ledger_user', table_name='bt2_dp_ledger')
    op.drop_table('bt2_dp_ledger')
    op.drop_table('bt2_behavioral_blocks')
    op.drop_index('ix_bt2_bankroll_user_date', table_name='bt2_bankroll_snapshots')
    op.drop_table('bt2_bankroll_snapshots')
    # ### end Alembic commands ###
