"""bt2_users_bankroll_cols

Revision ID: 9b79b90c69a1
Revises: 0a161c277233
Create Date: 2026-04-06 19:09:22.362488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b79b90c69a1'
down_revision: Union[str, Sequence[str], None] = '0a161c277233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bt2_users', sa.Column('bankroll_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('bt2_users', sa.Column('bankroll_currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bt2_users', 'bankroll_currency')
    op.drop_column('bt2_users', 'bankroll_amount')
    # ### end Alembic commands ###
