"""fix_odds_precision_10_4

Revision ID: c2d00bb2381b
Revises: 329bd4b9d494
Create Date: 2026-04-06 16:09:05.889730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d00bb2381b'
down_revision: Union[str, Sequence[str], None] = '329bd4b9d494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bt2_odds_snapshot', 'odds',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bt2_odds_snapshot', 'odds',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=6, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
