"""bt2_user_diagnostics_sprint04

Revision ID: dc2efb49e673
Revises: 33ad702e05ab
Create Date: 2026-04-07 12:04:00.657866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2efb49e673'
down_revision: Union[str, Sequence[str], None] = '33ad702e05ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bt2_user_diagnostics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('operator_profile', sa.String(length=50), nullable=False),
    sa.Column('system_integrity', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('answers_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bt2_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_diagnostics_user_created', 'bt2_user_diagnostics', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_diagnostics_user_created', table_name='bt2_user_diagnostics')
    op.drop_table('bt2_user_diagnostics')
    # ### end Alembic commands ###
